eth_threshold: 1            # ignore contracts with <1 ETH
chains:
  ethereum:
    rpc: https://eth-mainnet.alchemyapi.io/v2/KEY
    chain_id: 1
  base:
    rpc: https://base-mainnet.rpc-url/
    chain_id: 8453

telegram:
  enabled: true
  token: YOUR_BOT_TOKEN
  chat_id: YOUR_CHAT_ID
